version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - npm install -g aws-sam-cli
      - sam build

  build:
    commands:
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name net-stack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - template.yaml
